<!DOCTYPE html>
<!--
    Mahjong.html
    Written by: Johnathon Largent
    Version 1.0

   New game. Mahjong Solitaire (pair-matching tile layout), built on
   the shared engine.js + styles.css the same way every other game in
   the suite is: header, buttons, chips, toasts, hint-pulse, the
   Settings/Help/Win/Confirm modal shells, the undo stack, and the win
   cascade all come straight from engine.js/styles.css untouched. What
   this file owns is everything genuinely specific to Mahjong: the
   144-tile layered "turtle" layout, tile face art (tiles/*.svg, drawn
   the same way cards/*.webp are — real image files, one per tile
   design), the free-tile rule (nothing on top, open on the left or
   right), guaranteed-solvable deal generation, and click-to-select
   pair matching instead of drag/drop.

   Two settings this game adds that no card game needed:
     - Light/Dark tile color pickers (two <input type=color>) driving
       --tile-light/--tile-dark, which every tile's face gradient reads
       from live — tiles alternate between the two shades in a
       checkerboard based on board position, purely so adjacent/
       stacked tiles stay visually distinct from each other.
     - "Find Match" — mirrors Spider's find-next button, but the
       Mahjong equivalent of "where can this go" is "where's this
       tile's pair": select a tile, tap Find Match, and every
       CURRENTLY FREE tile sharing its match-group pulses. Only
       currently-free tiles ever pulse — like Spider's version, this
       never spoils a buried tile that isn't actually reachable yet.
-->
<!--
  Mahjong-specific rules:
    - 144 tiles across 4 layers (see TILE_LAYOUT below): 34 distinct
      "kinds" (9 Dots, 9 Bamboo, 9 Characters, 4 Winds, 3 Dragons) at 4
      copies each = 136, plus 4 Flowers + 4 Seasons (one of each design,
      no duplicates) = 144 total.
    - A tile is FREE (selectable) only if no other tile sits on top of
      it (any layer above whose footprint overlaps), AND at least one
      of its left/right neighbors at the same layer is empty.
    - Two free tiles match if they're the same kind, OR both are
      Flowers (any Flower matches any Flower), OR both are Seasons
      (same idea) — matched tiles are removed as a pair.
    - Deals are generated by actually solving the (kind-less) board
      layout with a random legal removal order first, THEN stamping
      matching kinds onto whichever two positions got "removed"
      together at each step — see generateSolvableLayout(). Since
      freeness only ever depends on position, not kind, that removal
      order stays 100% legal once kinds are assigned, so every fresh
      deal is guaranteed solvable start to finish.
    - Shuffle (bottom bar, and offered automatically if no matching
      pair remains) randomizes the kinds currently sitting on whatever
      tiles are still on the board. This does NOT re-run the solver —
      exactly like a real Mahjong Solitaire "shuffle" button, it can't
      guarantee the reshuffled board is still solvable, only that it's
      worth a fresh look.
-->
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=no">
<title>Mahjong</title>
<link rel="stylesheet" href="styles.css">
<style>
  /* ===== Mahjong-only background: plain dark jade vignette, same
     treatment Klondike uses for its felt-only look (no photo). ===== */
  html,body{
    background: radial-gradient(ellipse at 50% -10%, #182a1c, #0b140d 65%);
  }
  .brand .crest{ font-size:30px; }

  /* ===== Board ===== */
  .table-felt{ display:flex; align-items:center; justify-content:center; overflow:auto; }
  #board{ position:relative; margin:auto; flex-shrink:0; }

  /* --tile-light/--tile-dark are the two settings-driven colors; every
     tile reads one or the other depending on a checkerboard parity of
     its board position, purely to keep stacked/adjacent tiles visually
     distinct — see tileShadeVar() in the script below. */
  :root{
    --tile-light: #f6efdd;
    --tile-dark: #ddd0ac;
  }

  .mtile{
    position:absolute; left:0; top:0;
    cursor:pointer;
    transition: filter .15s ease, transform .12s ease;
  }
  .mtile-body{
    position:absolute; inset:0;
    border-radius: 14%;
    box-shadow:
      0 3px 0 rgba(0,0,0,.32),
      0 6px 10px rgba(0,0,0,.45),
      inset 0 0 0 1px rgba(255,255,255,.35),
      inset 0 -8px 12px rgba(0,0,0,.07);
  }
  .mtile-body img{
    position:absolute; inset:0; width:100%; height:100%;
    padding: 12%; box-sizing:border-box;
    object-fit:contain; pointer-events:none; user-select:none; display:block;
  }
  .mtile.blocked{ cursor:default; }
  .mtile.blocked .mtile-body{ filter: saturate(0.7) brightness(0.86); }
  .mtile.free:hover .mtile-body{ filter:brightness(1.07); }
  .mtile.free:active{ transform: translateY(1px); }
  .mtile.selected .mtile-body{
    box-shadow:
      0 0 0 4px #7ee6a8, 0 0 16px rgba(126,230,168,.75),
      0 3px 0 rgba(0,0,0,.32), 0 6px 10px rgba(0,0,0,.45);
  }

  /* ===== Settings: tile-color pickers ===== */
  .colorfield{ display:flex; align-items:center; justify-content:space-between; gap:12px; padding:4px 0; }
  .colorfield span{ font-size:14px; color:#e7f2ea; }
  .colorfield input[type=color]{
    width:44px; height:30px; border:1px solid var(--panel-line); border-radius:8px;
    background:none; padding:0; cursor:pointer;
  }

  .helpbody{ font-size:13px; line-height:1.7; color:#dce9df; }
  .helpbody b{ color:var(--brass-light); }
  .helpbody ul{ margin:6px 0 14px; padding-left:20px; }
</style>
</head>
<body>

<header>
  <div class="brand">
    <div class="crest">🀄</div>
    <div class="brand-text">
      <h1>Mahjong<span class="title-suffix"> &nbsp;·&nbsp; Solitaire</span></h1>
      <small>SOLITAIRE SUITE</small>
    </div>
    <div class="brand-actions">
      <a class="home-btn" href="index.html" title="Home">🏠</a>
      <button class="textbtn newgame-btn" id="btn-newgame">New Game</button>
    </div>
  </div>
  <div class="hud">
    <div class="chip" id="chip-score">Pairs <b id="score-val">0</b>/72</div>
    <div class="chip" id="chip-time">⏱ <b id="time-val">00:00</b></div>
    <div class="iconbtn" id="btn-help" title="Help">?</div>
    <div class="iconbtn" id="btn-settings" title="Settings">⚙</div>
  </div>
</header>

<div class="stage">
  <div class="table-frame">
    <div class="table-felt">
      <div id="board"></div>
    </div>
  </div>
</div>

<div class="bottombar">
  <div></div>
  <div class="bottombar-actions">
    <button class="bottombtn" id="btn-undo"><span class="bicon">↺</span><span class="blabel">UNDO</span></button>
    <button class="bottombtn" id="btn-hint"><span class="bicon">💡</span><span class="blabel">HINT</span></button>
    <button class="bottombtn" id="btn-findmatch"><span class="bicon">🔎</span><span class="blabel">FIND MATCH</span></button>
    <button class="bottombtn" id="btn-shuffle"><span class="bicon">🔀</span><span class="blabel">SHUFFLE</span></button>
  </div>
  <div></div>
</div>

<div class="hint-toast" id="toast"></div>

<!-- SETTINGS -->
<div class="overlay" id="settings-overlay">
  <div class="modal">
    <h3>Settings</h3>
    <div class="sub" id="version-info">Mahjong.html</div>

    <div class="field">
      <label>Tile Colors</label>
      <div class="colorfield"><span>Light tiles</span><input type="color" id="color-light"></div>
      <div class="colorfield"><span>Dark tiles</span><input type="color" id="color-dark"></div>
    </div>

    <div class="field">
      <div class="toggrow">
        <span>Show Timer</span>
        <label class="switch"><input type="checkbox" id="tog-timer"><span class="slider"></span></label>
      </div>
      <div class="toggrow">
        <span>Show Pairs Count</span>
        <label class="switch"><input type="checkbox" id="tog-score"><span class="slider"></span></label>
      </div>
      <div class="toggrow">
        <span>Show Find Match Button</span>
        <label class="switch"><input type="checkbox" id="tog-findmatch"><span class="slider"></span></label>
      </div>
    </div>

    <div class="modal-actions">
      <button class="textbtn" id="settings-cancel">Cancel</button>
      <button class="textbtn primary" id="settings-apply">Apply</button>
      <button class="textbtn primary" id="settings-newgame">Apply &amp; New Game</button>
    </div>
  </div>
</div>

<!-- HELP -->
<div class="overlay" id="help-overlay">
  <div class="modal">
    <h3>How To Play</h3>
    <div class="sub">Mahjong Solitaire</div>
    <div class="helpbody">
      <p>Clear all 144 tiles by matching them in pairs.</p>
      <ul>
        <li>Tap a tile to select it, then tap a matching tile to remove both.</li>
        <li>Only <b>free</b> tiles can be selected — nothing covering it from
        above, and at least one open side (left or right).</li>
        <li>Two tiles match if they're the exact same tile, or if both are
        <b>Flowers</b> (any Flower matches any Flower), or both are
        <b>Seasons</b> (same idea).</li>
        <li><b>Hint</b> pulses any one currently-available matching pair.</li>
        <li><b>Find Match</b> pulses every free tile matching your current
        selection.</li>
        <li><b>Shuffle</b> randomizes the kinds on whatever tiles remain —
        useful if you get stuck.</li>
      </ul>
    </div>
    <div class="modal-actions">
      <button class="textbtn primary" id="help-close">Got it</button>
    </div>
  </div>
</div>

<!-- CONFIRM NEW GAME -->
<div class="overlay" id="confirm-overlay">
  <div class="modal">
    <h3>Start Over?</h3>
    <div class="sub">Your current board will be lost.</div>
    <div class="modal-actions">
      <button class="textbtn" id="confirm-cancel">Cancel</button>
      <button class="textbtn primary" id="confirm-yes">New Game</button>
    </div>
  </div>
</div>

<!-- NO MOVES -->
<div class="overlay" id="nomovesmask">
  <div class="modal">
    <h3>No Moves Left</h3>
    <div class="sub">There's no matching pair currently free.</div>
    <div class="modal-actions">
      <button class="textbtn" id="nomoves-undo">Undo</button>
      <button class="textbtn" id="nomoves-shuffle">Shuffle</button>
      <button class="textbtn primary" id="nomoves-newgame">New Game</button>
    </div>
  </div>
</div>

<!-- WIN -->
<div class="winmask" id="winmask">
  <div class="winmask-modal">
    <h2>Board Cleared!</h2>
    <p id="win-time-line">Time: 00:00</p>
    <button class="textbtn primary" id="win-newgame">Play Again</button>
  </div>
</div>

<script src="engine.js"></script>
<script>
(function(){
"use strict";
const E = SEngine;
const PAGE_VERSION = '1.0';

/* =========================================================
   TILE LAYOUT
   [layer, col, row] — col/row are in half-tile "grid units" (a tile
   is 2 units wide/tall), so same-layer neighbors sit exactly 2 units
   apart and cross-layer overlap is a simple bounding-box test. 4
   layers, 144 total positions: 84 + 40 + 12 + 8, each layer centered
   over the one below it (with a deliberate half-unit stagger between
   some layers — the same brick-like interlock real tile sets use).
   ========================================================= */
const TILE_LAYOUT = [
[0,0,0],[0,2,0],[0,4,0],[0,6,0],[0,8,0],[0,10,0],[0,12,0],[0,14,0],[0,16,0],[0,18,0],[0,20,0],[0,22,0],[0,24,0],[0,26,0],[0,0,2],[0,2,2],[0,4,2],[0,6,2],[0,8,2],[0,10,2],[0,12,2],[0,14,2],[0,16,2],[0,18,2],[0,20,2],[0,22,2],[0,24,2],[0,26,2],[0,0,4],[0,2,4],[0,4,4],[0,6,4],[0,8,4],[0,10,4],[0,12,4],[0,14,4],[0,16,4],[0,18,4],[0,20,4],[0,22,4],[0,24,4],[0,26,4],[0,0,6],[0,2,6],[0,4,6],[0,6,6],[0,8,6],[0,10,6],[0,12,6],[0,14,6],[0,16,6],[0,18,6],[0,20,6],[0,22,6],[0,24,6],[0,26,6],[0,0,8],[0,2,8],[0,4,8],[0,6,8],[0,8,8],[0,10,8],[0,12,8],[0,14,8],[0,16,8],[0,18,8],[0,20,8],[0,22,8],[0,24,8],[0,26,8],[0,0,10],[0,2,10],[0,4,10],[0,6,10],[0,8,10],[0,10,10],[0,12,10],[0,14,10],[0,16,10],[0,18,10],[0,20,10],[0,22,10],[0,24,10],[0,26,10],[1,3,1],[1,5,1],[1,7,1],[1,9,1],[1,11,1],[1,13,1],[1,15,1],[1,17,1],[1,19,1],[1,21,1],[1,3,3],[1,5,3],[1,7,3],[1,9,3],[1,11,3],[1,13,3],[1,15,3],[1,17,3],[1,19,3],[1,21,3],[1,3,5],[1,5,5],[1,7,5],[1,9,5],[1,11,5],[1,13,5],[1,15,5],[1,17,5],[1,19,5],[1,21,5],[1,3,7],[1,5,7],[1,7,7],[1,9,7],[1,11,7],[1,13,7],[1,15,7],[1,17,7],[1,19,7],[1,21,7],[2,7,3],[2,9,3],[2,11,3],[2,13,3],[2,15,3],[2,17,3],[2,7,5],[2,9,5],[2,11,5],[2,13,5],[2,15,5],[2,17,5],[3,9,3],[3,11,3],[3,13,3],[3,15,3],[3,9,5],[3,11,5],[3,13,5],[3,15,5]
];

const KINDS_34 = [
  'dot_1','dot_2','dot_3','dot_4','dot_5','dot_6','dot_7','dot_8','dot_9',
  'bam_1','bam_2','bam_3','bam_4','bam_5','bam_6','bam_7','bam_8','bam_9',
  'char_1','char_2','char_3','char_4','char_5','char_6','char_7','char_8','char_9',
  'wind_E','wind_S','wind_W','wind_N',
  'dragon_red','dragon_green','dragon_white'
];
const FLOWER_KINDS = ['flower_1','flower_2','flower_3','flower_4'];
const SEASON_KINDS = ['season_1','season_2','season_3','season_4'];

function tileImgSrc(kind){ return 'tiles/'+kind+'.svg'; }
function groupOf(kind){
  if(kind.indexOf('flower')===0) return 'flower';
  if(kind.indexOf('season')===0) return 'season';
  return kind;
}

/* =========================================================
   STATE
   ========================================================= */
let state = {
  tiles: [],           // {id, layer, col, row, kind, removed}
  selectedId: null,
  matchedCount: 0,
  showTimer: true,
  showScore: true,
  findMatchEnabled: true,
  tileLight: '#f6efdd',
  tileDark: '#ddd0ac',
  elapsedSeconds: 0
};
let pendingSettings = {};
let timerInterval = null;
const toastEl = document.getElementById('toast');

/* =========================================================
   GEOMETRY HELPERS
   ========================================================= */
function overlaps(a, b){
  return a.col < b.col+2 && a.col+2 > b.col && a.row < b.row+2 && a.row+2 > b.row;
}
// isFree against an arbitrary active list (used both by the solver,
// where "active" shrinks as positions get virtually removed, and by
// real gameplay, where "active" is simply every non-removed tile).
function isFreeAmong(tile, activeList){
  for(const t of activeList){
    if(t===tile) continue;
    if(t.layer > tile.layer && overlaps(t, tile)) return false;
  }
  let leftOpen = true, rightOpen = true;
  for(const t of activeList){
    if(t===tile) continue;
    if(t.layer===tile.layer && t.row===tile.row){
      if(t.col === tile.col-2) leftOpen = false;
      if(t.col === tile.col+2) rightOpen = false;
    }
  }
  return leftOpen || rightOpen;
}
function activeTiles(){ return state.tiles.filter(t=>!t.removed); }
function isFreeRuntime(tile){ return isFreeAmong(tile, activeTiles()); }

/* =========================================================
   SOLVABLE DEAL GENERATION
   Simulates an actual legal removal of the (kind-less) layout in
   random order, recording which two positions got "removed" together
   at each step, then stamps a matching pair of kinds onto exactly
   those two positions. Freeness only depends on position, never kind,
   so replaying that same removal order in the real game is always
   still legal — guaranteeing the fresh deal is solvable.
   ========================================================= */
function generateSolvableLayout(){
  const positions = TILE_LAYOUT.map((p,i)=>({ id:'t'+i, layer:p[0], col:p[1], row:p[2], kind:null, removed:false }));

  const pairSlots = [];
  KINDS_34.forEach(k=>{ pairSlots.push(k, k); });
  pairSlots.push('FLOWER','FLOWER');
  pairSlots.push('SEASON','SEASON');
  E.shuffle(pairSlots);

  const flowerPool = E.shuffle(FLOWER_KINDS.slice());
  const seasonPool = E.shuffle(SEASON_KINDS.slice());

  let active = positions.slice();
  let guard = 0;
  while(pairSlots.length && guard++ < 10000){
    const free = active.filter(p=> isFreeAmong(p, active));
    if(free.length < 2){
      // Extremely unlikely with this layout, but fall back to any two
      // remaining active positions rather than looping forever.
      free.length = 0;
      free.push(active[0], active[1]);
    }
    E.shuffle(free);
    const posA = free[0], posB = free[1];
    const slot = pairSlots.pop();
    if(slot === 'FLOWER'){
      posA.kind = flowerPool.pop();
      posB.kind = flowerPool.pop();
    } else if(slot === 'SEASON'){
      posA.kind = seasonPool.pop();
      posB.kind = seasonPool.pop();
    } else {
      posA.kind = slot; posB.kind = slot;
    }
    active = active.filter(p=> p!==posA && p!==posB);
  }
  return positions;
}

/* =========================================================
   FIT / LAYOUT-TO-PIXELS
   ========================================================= */
let tileW = 46, tileH = 60;
const TILE_ASPECT = 260/200;
const LAYER_SHIFT = 4; // px each axis, purely a "stacked height" visual cue

function boardBounds(){
  let maxCol=0, maxRow=0;
  TILE_LAYOUT.forEach(p=>{ if(p[1]+2>maxCol) maxCol=p[1]+2; if(p[2]+2>maxRow) maxRow=p[2]+2; });
  return { unitsW:maxCol, unitsH:maxRow };
}
function fitBoard(){
  const felt = document.querySelector('.table-felt');
  if(!felt) return;
  const bounds = boardBounds();
  const feltCS = getComputedStyle(felt);
  const vPad = parseFloat(feltCS.paddingTop)+parseFloat(feltCS.paddingBottom);
  const hPad = parseFloat(feltCS.paddingLeft)+parseFloat(feltCS.paddingRight);
  const availW = felt.clientWidth - hPad - (LAYER_SHIFT*4) - 6;
  const availH = felt.clientHeight - vPad - (LAYER_SHIFT*4) - 6;

  const halfUnitsW = bounds.unitsW/2;
  const halfUnitsH = bounds.unitsH/2;

  let byWidth = availW / halfUnitsW;
  let byHeight = (availH / halfUnitsH) / TILE_ASPECT;
  let w = Math.max(14, Math.min(byWidth, byHeight, 72));
  tileW = Math.round(w);
  tileH = Math.round(tileW * TILE_ASPECT);

  const boardEl = document.getElementById('board');
  boardEl.style.width = (bounds.unitsW/2*tileW + LAYER_SHIFT*3) + 'px';
  boardEl.style.height = (bounds.unitsH/2*tileH + LAYER_SHIFT*3) + 'px';
}

/* =========================================================
   RENDER
   ========================================================= */
function tileEl(id){ return document.querySelector('.mtile[data-id="'+id+'"]'); }
function findTile(id){ return state.tiles.find(t=>t.id===id); }

// Alternates the two settings-driven tile colors in a checkerboard
// based on board position, purely so overlapping/adjacent tiles read
// as visually distinct blocks rather than one solid mass.
function tileShadeColor(t){
  const parity = ((t.col/2) + (t.row/2) + t.layer) % 2;
  return parity===0 ? 'var(--tile-light)' : 'var(--tile-dark)';
}

function renderAll(){
  E.purgeStrayCards(); // harmless no-op here, kept for parity with the other games' render entry point
  const boardEl = document.getElementById('board');
  boardEl.innerHTML = '';
  const halfW = tileW/2, halfH = tileH/2;
  const active = activeTiles();
  active.forEach(t=>{
    const free = isFreeAmong(t, active);
    const el = document.createElement('div');
    el.className = 'mtile ' + (free ? 'free' : 'blocked') + (state.selectedId===t.id ? ' selected' : '');
    el.dataset.id = t.id;
    const left = (t.col/2)*tileW - t.layer*LAYER_SHIFT;
    const top = (t.row/2)*tileH - t.layer*LAYER_SHIFT;
    el.style.left = left + 'px';
    el.style.top = top + 'px';
    el.style.width = tileW + 'px';
    el.style.height = tileH + 'px';
    el.style.zIndex = String(t.layer*1000 + t.row*20 + t.col);

    const body = document.createElement('div');
    body.className = 'mtile-body';
    body.style.background = 'linear-gradient(160deg, ' + tileShadeColor(t) + ', ' + tileShadeColor(t) + ')';
    // Real two-tone gradient (light->dark) layered on top of the
    // checkerboard base color, so every tile still reads as a
    // rounded, lit block regardless of which shade it landed on.
    body.style.backgroundImage = 'linear-gradient(160deg, rgba(255,255,255,.35), rgba(0,0,0,.06)), linear-gradient(160deg, '+tileShadeColor(t)+', '+tileShadeColor(t)+')';

    const img = document.createElement('img');
    img.src = tileImgSrc(t.kind);
    img.alt = t.kind;
    img.draggable = false;
    body.appendChild(img);
    el.appendChild(body);

    el.addEventListener('click', ()=> onTileClick(t.id));
    boardEl.appendChild(el);
  });
  updateHud();
}

function updateHud(){
  document.getElementById('score-val').textContent = String(state.matchedCount);
  const mm = String(Math.floor(state.elapsedSeconds/60)).padStart(2,'0');
  const ss = String(state.elapsedSeconds%60).padStart(2,'0');
  document.getElementById('time-val').textContent = mm+':'+ss;
  E.applyHudVisibility(state);
  document.getElementById('btn-findmatch').style.display = state.findMatchEnabled ? 'flex' : 'none';
}

/* =========================================================
   TIMER
   ========================================================= */
function syncTimerInterval(){
  clearInterval(timerInterval);
  if(state.showTimer){
    timerInterval = setInterval(()=>{
      state.elapsedSeconds++;
      updateHud();
    }, 1000);
  }
}

/* =========================================================
   UNDO
   ========================================================= */
const undo = E.createUndoStack(
  ()=>({ tiles: state.tiles.map(t=>({id:t.id, removed:t.removed})), matchedCount: state.matchedCount }),
  (snap)=>{
    const byId = {};
    snap.tiles.forEach(s=> byId[s.id]=s.removed);
    state.tiles.forEach(t=>{ t.removed = !!byId[t.id]; });
    state.matchedCount = snap.matchedCount;
    state.selectedId = null;
    document.getElementById('nomovesmask').classList.remove('show');
    renderAll();
  },
  document.getElementById('btn-undo')
);

/* =========================================================
   GAME LOGIC
   ========================================================= */
function matches(kindA, kindB){ return groupOf(kindA)===groupOf(kindB); }

function onTileClick(id){
  const t = findTile(id);
  if(!t || t.removed) return;
  if(!isFreeRuntime(t)){ E.showToast(toastEl, 'That tile is blocked.'); return; }

  if(state.selectedId === id){
    state.selectedId = null;
    renderAll();
    return;
  }
  if(state.selectedId){
    const other = findTile(state.selectedId);
    if(other && !other.removed && matches(other.kind, t.kind)){
      undo.push();
      other.removed = true;
      t.removed = true;
      state.matchedCount++;
      state.selectedId = null;
      renderAll();
      checkWinOrStuck();
      return;
    }
  }
  state.selectedId = id;
  renderAll();
}

function findAnyFreePair(){
  const free = activeTiles().filter(isFreeRuntime);
  for(let i=0;i<free.length;i++){
    for(let j=i+1;j<free.length;j++){
      if(matches(free[i].kind, free[j].kind)) return [free[i], free[j]];
    }
  }
  return null;
}
function hasAnyMove(){ return !!findAnyFreePair(); }

function checkWinOrStuck(){
  if(activeTiles().length === 0){
    clearInterval(timerInterval);
    const mm = String(Math.floor(state.elapsedSeconds/60)).padStart(2,'0');
    const ss = String(state.elapsedSeconds%60).padStart(2,'0');
    document.getElementById('win-time-line').textContent = 'Time: '+mm+':'+ss;
    document.getElementById('winmask').classList.add('show');
    return;
  }
  if(!hasAnyMove()){
    document.getElementById('nomovesmask').classList.add('show');
  }
}

function shuffleRemaining(){
  const active = activeTiles();
  const kinds = active.map(t=>t.kind);
  let tries = 0;
  do{
    E.shuffle(kinds);
    tries++;
  } while(tries < 30 && !shuffleHasMove(active, kinds));
  active.forEach((t,i)=>{ t.kind = kinds[i]; });
  state.selectedId = null;
  renderAll();
  checkWinOrStuck();
}
function shuffleHasMove(active, kinds){
  const free = active.filter(t=> isFreeAmong(t, active));
  const idxOf = {};
  active.forEach((t,i)=> idxOf[t.id]=i);
  for(let i=0;i<free.length;i++){
    for(let j=i+1;j<free.length;j++){
      if(groupOf(kinds[idxOf[free[i].id]]) === groupOf(kinds[idxOf[free[j].id]])) return true;
    }
  }
  return false;
}

function newGame(){
  document.getElementById('winmask').classList.remove('show');
  document.getElementById('nomovesmask').classList.remove('show');
  state.tiles = generateSolvableLayout();
  state.selectedId = null;
  state.matchedCount = 0;
  state.elapsedSeconds = 0;
  undo.reset();
  fitBoard();
  renderAll();
  syncTimerInterval();
}

/* =========================================================
   SETTINGS WIRING
   ========================================================= */
function applyTileColors(){
  document.documentElement.style.setProperty('--tile-light', state.tileLight);
  document.documentElement.style.setProperty('--tile-dark', state.tileDark);
}
function refreshVersionInfo(){
  const stylesVersion = E.getStylesheetVersion() || 'unknown';
  document.getElementById('version-info').textContent =
    'Mahjong.html v'+PAGE_VERSION+' · engine.js v'+E.ENGINE_VERSION+' · styles.css v'+stylesVersion;
}

let settingsSnapshot = null;
function openSettings(){
  settingsSnapshot = {
    showTimer: state.showTimer, showScore: state.showScore, findMatchEnabled: state.findMatchEnabled,
    tileLight: state.tileLight, tileDark: state.tileDark
  };
  document.getElementById('tog-timer').checked = state.showTimer;
  document.getElementById('tog-score').checked = state.showScore;
  document.getElementById('tog-findmatch').checked = state.findMatchEnabled;
  document.getElementById('color-light').value = state.tileLight;
  document.getElementById('color-dark').value = state.tileDark;
  refreshVersionInfo();
  document.getElementById('settings-overlay').classList.add('show');
}
function revertSettings(){
  if(!settingsSnapshot) return;
  state.showTimer = settingsSnapshot.showTimer;
  state.showScore = settingsSnapshot.showScore;
  state.findMatchEnabled = settingsSnapshot.findMatchEnabled;
  state.tileLight = settingsSnapshot.tileLight;
  state.tileDark = settingsSnapshot.tileDark;
  applyTileColors();
  syncTimerInterval();
  updateHud();
}
document.getElementById('tog-timer').addEventListener('change', e=>{ state.showTimer = e.target.checked; syncTimerInterval(); updateHud(); });
document.getElementById('tog-score').addEventListener('change', e=>{ state.showScore = e.target.checked; updateHud(); });
document.getElementById('tog-findmatch').addEventListener('change', e=>{ state.findMatchEnabled = e.target.checked; updateHud(); });
document.getElementById('color-light').addEventListener('input', e=>{ state.tileLight = e.target.value; applyTileColors(); });
document.getElementById('color-dark').addEventListener('input', e=>{ state.tileDark = e.target.value; applyTileColors(); });

document.getElementById('btn-settings').addEventListener('click', openSettings);
document.getElementById('settings-cancel').addEventListener('click', ()=>{
  revertSettings();
  document.getElementById('settings-overlay').classList.remove('show');
});
document.getElementById('settings-apply').addEventListener('click', ()=>{
  document.getElementById('settings-overlay').classList.remove('show');
});
document.getElementById('settings-newgame').addEventListener('click', ()=>{
  document.getElementById('settings-overlay').classList.remove('show');
  newGame();
});
document.getElementById('settings-overlay').addEventListener('click', (e)=>{
  if(e.target===document.getElementById('settings-overlay')){
    revertSettings();
    document.getElementById('settings-overlay').classList.remove('show');
  }
});

/* =========================================================
   BUTTONS
   ========================================================= */
document.getElementById('btn-help').addEventListener('click', ()=> document.getElementById('help-overlay').classList.add('show'));
document.getElementById('help-close').addEventListener('click', ()=> document.getElementById('help-overlay').classList.remove('show'));
document.getElementById('help-overlay').addEventListener('click', (e)=>{ if(e.target===document.getElementById('help-overlay')) document.getElementById('help-overlay').classList.remove('show'); });

const confirmOverlay = document.getElementById('confirm-overlay');
document.getElementById('btn-newgame').addEventListener('click', ()=> confirmOverlay.classList.add('show'));
document.getElementById('confirm-cancel').addEventListener('click', ()=> confirmOverlay.classList.remove('show'));
document.getElementById('confirm-yes').addEventListener('click', ()=>{ confirmOverlay.classList.remove('show'); newGame(); });
confirmOverlay.addEventListener('click', (e)=>{ if(e.target===confirmOverlay) confirmOverlay.classList.remove('show'); });

document.getElementById('btn-undo').addEventListener('click', ()=> undo.undo());

document.getElementById('btn-hint').addEventListener('click', ()=>{
  state.selectedId = null;
  const pair = findAnyFreePair();
  if(!pair){ E.showToast(toastEl, 'No matching pair currently free.'); return; }
  renderAll();
  const els = [tileEl(pair[0].id), tileEl(pair[1].id)].filter(Boolean);
  E.pulseAll(els, 1200);
});

document.getElementById('btn-findmatch').addEventListener('click', ()=>{
  if(!state.selectedId){ E.showToast(toastEl, 'Select a tile first.'); return; }
  const sel = findTile(state.selectedId);
  const free = activeTiles().filter(t=> t.id!==sel.id && isFreeRuntime(t) && matches(t.kind, sel.kind));
  if(!free.length){ E.showToast(toastEl, 'No available match for that tile right now.'); return; }
  const els = free.map(t=> tileEl(t.id)).filter(Boolean);
  E.pulseAll(els, 1200);
});

document.getElementById('btn-shuffle').addEventListener('click', ()=>{
  undo.push();
  shuffleRemaining();
});

document.getElementById('nomoves-undo').addEventListener('click', ()=>{
  document.getElementById('nomovesmask').classList.remove('show');
  undo.undo();
});
document.getElementById('nomoves-shuffle').addEventListener('click', ()=>{
  document.getElementById('nomovesmask').classList.remove('show');
  undo.push();
  shuffleRemaining();
});
document.getElementById('nomoves-newgame').addEventListener('click', ()=>{
  document.getElementById('nomovesmask').classList.remove('show');
  newGame();
});
document.getElementById('win-newgame').addEventListener('click', ()=>{
  document.getElementById('winmask').classList.remove('show');
  newGame();
});

let resizeTimer = null;
window.addEventListener('resize', ()=>{
  clearTimeout(resizeTimer);
  resizeTimer = setTimeout(()=>{ fitBoard(); renderAll(); }, 100);
});

/* =========================================================
   INIT
   ========================================================= */
applyTileColors();
newGame();

})();
</script>
</body>
</html>
